import './globals.css';
import Provider from '@/context/AuthContext';
import { Navigation } from '@/components/Navigation';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <Provider>
          <Navigation>{children}</Navigation>
        </Provider>
      </body>
    </html>
  );
}
