import './globals.css';
import { Open_Sans } from 'next/font/google';
import AuthProvider from '@/providers/AuthProvider';
import ThemeProvider from '@/providers/ThemeProvider';
import TrpcProvider from '@/providers/TrpcProvider';
import { Toaster } from '@/components/ui/toaster';

const opensans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={opensans.className}>
        <AuthProvider>
          <TrpcProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {children}
              <Toaster />
            </ThemeProvider>
          </TrpcProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
